### ISSUE TITLE
Dynamic keys and/or map structures in JSON

### ISSUE THREAD

**Issue by impredicative** [stickfigure/blog#1]
Regarding https://github.com/stickfigure/blog/wiki/How-to-(and-how-not-to)-design-REST-APIs/1a31d1a55f075d0c4460b592e2a95258bc4e6cbb#rule-5-dont-return-map-structures , I consider it a limitation of the tooling if it can't handle dynamic keys and/or map structures, even ordered keys. Yes, an array can just be used, but I do think that typed languages need to step up and allow JSON to be used to its fullest. You yourself have a weird exception to your own rule when it suits you.

**Comment by stickfigure** [comment]
Sorry, not using github issues as a discussion forum - consider posting in the linked HN thread?

(disabling issues)
