### ISSUE TITLE
Numeric identifiers

### ISSUE THREAD

**Issue by impredicative** [stickfigure/blog#2]
No, there is no convincing reason in https://github.com/stickfigure/blog/wiki/How-to-(and-how-not-to)-design-REST-APIs/1a31d1a55f075d0c4460b592e2a95258bc4e6cbb#rule-6-do-use-strings-for-all-identifiers to discourage the use of integers as identifiers. It's an ultra weak argument.

**Comment by stickfigure** [comment]
Sorry, not using github issues as a discussion forum - consider posting in the linked HN thread?

(disabling issues)
